version: "3"
services:
  frontend:
    volumes:
      - $PWD/frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "35729:35729"
  backend:
    environment:
      - NODE_ENV=development
    ports:
      - "5000:8080"
networks:
  webnet:
