version: "3"
services:
  backend:
    image: benjithedalilama/alice-backend:MVP
    environment:
      - NODE_ENV=production
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - webnet
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - webnet
networks:
  webnet:
