version: "3"
services:
  frontend:
    image: benjithedalilama/alice:MVP-frontend
    volumes:
      - $PWD/frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "35729:35729"
    networks:
      - webnet
  backend:
    image: benjithedalilama/alice:MVP
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=development
    ports:
      - "5000:8080"
    networks:
      - webnet
networks:
  webnet:
