version: "3"
services:
  web:
    image: benjithedalilama/alice:MVP-frontend
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "1337:80"
    networks:
      - webnet
  app:
    image: benjithedalilama/alice:MVP
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:8080"
    networks:
      - webnet
networks:
  webnet:
