version: "3"
services:
  frontend:
    image: benjithedalilama/alice:MVP-frontend
    environment:
      - NODE_ENV=production
    networks:
      - webnet
  backend:
    image: benjithedalilama/alice:MVP
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production
    networks:
      - webnet
networks:
  webnet:
