version: "3"
services:
  frontend:
    image: benjithedalilama/alice:MVP-frontend
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - webnet
  backend:
    image: benjithedalilama/alice:MVP
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - webnet
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - webnet
networks:
  webnet:
