# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - v2-frontend-dependencies
            - v2-backend-dependencies

      - checkout

      - run: cd frontend && yarn install

      - save_cache:
          paths:
            - frontend/node_modules
          key:
            - v2-frontend-dependencies

      - run: cd frontend && yarn test

      - run: cd backend && yarn install

      - save_cache:
          paths:
            - ./backend/node_modules
          key:
            - v2-backend-dependencies

      - run: cd backend && yarn test
